### ISSUE TITLE
domain_users

### ISSUE THREAD

**Issue by stoplik** [stoplik/TEST#4]
Ak vyprintujem cely zoznam domain userov, tak zaciatok je este nejakych par riadkov text (The request will be processed at a domain controller..), z ktoreho sme vlastne spravili list a to neviem ako urobit tak, aby tieto riadky python neprechadzal.
Lebo teraz sme to robili na sample useroch (test.txt), ktory som si vybrala z domain userov, no ak to chceme uplne zautomatizovat, tak este neviem ako sa zbavime tych par riadkov textu, kym sa dostanem k listu userov.

**Comment by minkomi** [comment]
stále je to fixná dĺžka toho textu, že? tak pracovať len od riadku kde toto nie je.. alebo na celý výsledok dať replace("celý ten text...", "") a nahradiť ničím - teda neviem aký je presný syntax v pythone.., a až potom spracovávať.
Ináč GOOD JOB !!! ľúbi sa mi to.. =)

**Comment by stoplik** [comment]
Python zacne citat po 6-tom riadku a nebude citat 4 riadky od konca
file='domain_users.txt'
with open(file) as f:
    lines_after_6 = f.readlines()[6:-4]
